#!/usr/bin/node
var cp = require('child_process');
var fs = require('fs');
var net = require('net');
if (process.pid == 1) {
console.log('Welcome to Lenux v1.0.3!');
console.log('Initializing daemons...');
fs.readdir('/etc/init', function(err, data) {
  if (err) {
    console.log('ERROR: MISSING INIT DIRECTORY OR NOT READABLE');
    console.log('UNRECOVERABLE: ENTERING INFINITE LOOP');
    while(true);
  }
  else {
    for (var i = 0; i < data.length; i++) {
      var daemon = data[i];
      console.log('Starting ' + daemon + '...');
      fs.readFile('/etc/init/' + daemon, function(err, filedata) {
        if (err) {
          console.log('WARNING: Could not read initfile ' + daemon + ', skipping');
        }
        else {
          var progargs = filedata.toString().split('\n')[0].split(' ');
          var progname = progargs.shift();
          function startProgram(daemon) {
            var program = cp.spawn(progname, progargs);
            program.stdout.pipe(process.stdout);
            program.stderr.pipe(process.stderr);
            program.on('close', function() {
              console.log('Restarting ' + daemon + '...');
              startProgram(daemon);
            });
          }
          startProgram(daemon);
        }
      });
    }
    console.log('System initialized!');
  }
});
}
else {
  console.log('PID is not 1, init must be started by kernel on boot.');
}
